### ISSUE TITLE
Je refais tourner les tests, y en a trois qui marchent plus

### ISSUE THREAD

**Issue by Mendelrock** [Frakh/Champions-of-Strength-and-Sorcery#1]
CombatTest, MapTest et MouseTest ne marchent pas. Je soupçonne que Paul est en train de travailler sur MapTest et MouseTest, mais CombatTest me dérange...

**Comment by CfwIA** [comment]
MouseTest se remet a marcher ( j'ai oublié un new... ) Il devrait marcher

**Comment by CfwIA** [comment]
MapTest remarche, pour le reste, adresse toi au gros vin #Gragas

**Comment by ghost** [comment]
FTFY
